name: preview-site-build

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  tdesign-miniprogram-site:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }} > pr-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 5

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: pnpm install

      - run: pnpm -C packages/tdesign-miniprogram/site run site:preview

      - uses: actions/upload-artifact@v4
        with:
          name: tdesign-miniprogram-site
          path: packages/tdesign-miniprogram/site/dist
          retention-days: 5

  tdesign-miniprogram-chat-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: pnpm install

      - run: pnpm -C packages/tdesign-miniprogram-chat/site run site:preview

      - uses: actions/upload-artifact@v4
        with:
          name: tdesign-miniprogram-chat-site
          path: packages/tdesign-miniprogram-chat/site/dist
          retention-days: 5

  tdesign-uniapp-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: pnpm install

      - run: pnpm -C packages/tdesign-uniapp/site run site:preview

      - uses: actions/upload-artifact@v4
        with:
          name: tdesign-uniapp-site
          path: packages/tdesign-uniapp/site/dist
          retention-days: 5

  tdesign-uniapp-chat-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: pnpm install

      - run: pnpm -C packages/tdesign-uniapp-chat/site run site:preview

      - uses: actions/upload-artifact@v4
        with:
          name: tdesign-uniapp-chat-site
          path: packages/tdesign-uniapp-chat/site/dist
          retention-days: 5
