default.check-filename = true

[default.extend-words]
actived = "actived"
Colum = "Colum"
ded = "ded"
destory ="destory"
nd = "nd"
loosing = "loosing"

[files]
extend-exclude = [
  "CHANGELOG*.md", 
  "changelog.json", 
  "echarts.js",
  "packages/tdesign-uniapp/components/npm/**/*",
  "packages/tdesign-uniapp-chat/components/npm/**/*",
  "packages/tdesign-uniapp/app/common/uni.css",
  "packages/tdesign-uniapp/app/uni_modules/**/*",
]
